/**
 * @fileoverview Print Page Component
 * 
 * Full page layout for print-ready chart with controls and legend.
 * Designed for high-resolution export and printing.
 * 
 * @author UNICEF/Radial Interactive Team
 * @version 2.0.0
 */

import { useRef } from 'react';
import PrintRadialChart from './PrintRadialChart';
import PrintControls from './components/PrintControls';

// STEEP Categories for legend - exact same as original
const STEEP_CATEGORIES = [
  { name: 'Social', color: '#00A6FB' },
  { name: 'Technological', color: '#7B68EE' },
  { name: 'Economic', color: '#FFB800' },
  { name: 'Environmental', color: '#00C853' },
  { name: 'Political & Legal', color: '#FF5252' }
];

function PrintPage() {
  const svgRef = useRef(null);

  const navigateToInteractive = () => {
    window.location.hash = '';
  };

  return (
    <div className="min-h-screen bg-white relative">
      {/* Header */}
      <header className="text-center py-6 px-4">
        <h1 className="text-3xl font-bold text-blue-600 mb-2">
          UNICEF Youth Foresight Fellows
        </h1>
        <p className="text-2xl font-bold text-gray-600">
          Interactive Signal of Change Radar
        </p>
        <p className="text-lg text-gray-500 mt-2">
          Print-Ready Version
        </p>
      </header>

      {/* Print Controls - Upper Right */}
      <PrintControls svgRef={svgRef} />

      {/* Navigation to Interactive Version - Upper Left */}
      <div className="absolute top-4 left-4 z-10">
        <button
          onClick={navigateToInteractive}
          className="bg-gray-600 hover:bg-gray-700 text-white font-medium py-2 px-4 rounded-lg shadow-lg transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2"
        >
          ← Interactive Version
        </button>
      </div>

      {/* Main Chart Area */}
      <div className="flex justify-center items-start px-4 pb-4">
        <div className="relative w-full max-w-6xl">
          {/* Chart Container */}
          <div className="relative">
            <PrintRadialChart ref={svgRef} />
          </div>

          {/* Legend - Lower Left Corner */}
          <div className="absolute bottom-4 left-4 bg-white rounded-lg shadow-lg p-4 border border-gray-200 max-w-xs">
            <h3 className="text-lg font-semibold text-gray-800 mb-3">STEEP Categories</h3>
            
            {/* STEEP Categories */}
            <div className="space-y-2 mb-4">
              {STEEP_CATEGORIES.map((category) => (
                <div key={category.name} className="flex items-center gap-3">
                  <div 
                    className="w-4 h-4 rounded-full flex-shrink-0"
                    style={{ backgroundColor: category.color }}
                  />
                  <span className="text-sm font-medium text-gray-700">
                    {category.name}
                  </span>
                </div>
              ))}
            </div>

            {/* Participant-identified signals */}
            <div className="flex items-center gap-3 pt-2 border-t border-gray-200">
              <svg width="16" height="16" viewBox="0 0 24 24" className="text-yellow-500 flex-shrink-0">
                <path 
                  d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" 
                  fill="currentColor"
                />
              </svg>
              <span className="text-sm font-medium text-gray-700">
                Participant-identified signals
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="text-center py-4 px-4 border-t border-gray-200">
        <p className="text-sm text-gray-500">
          Generated by UNICEF Interactive Signal of Change Radar
        </p>
        <p className="text-xs text-gray-400 mt-1">
          High-resolution export available in SVG and PNG formats
        </p>
      </footer>
    </div>
  );
}

export default PrintPage;
